### ISSUE TITLE
embedding_extract error after uplaod  file and load database

### ISSUE THREAD

**Issue by panjie-payne** [RapidAI/Knowledge-QA-LLM#10]
这个什么情况呀带佬

Traceback (most recent call last):
  File "/Users/panjie/anaconda3/envs/knowledge-base/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/payne/codes/AI/Knowledge-QA-LLM/webui.py", line 218, in <module>
    init_sidebar()
  File "/Users/payne/codes/AI/Knowledge-QA-LLM/webui.py", line 102, in init_sidebar
    print(embedding_extract)
NameError: name 'embedding_extract' is not defined

**Comment by SWHL** [comment]
用最新代码`tag=v0.0.7`，我猜你跑的不是最新的。

**Comment by panjie-payne** [comment]
> 用最新代码`tag=v0.0.7`，我猜你跑的不是最新的。

我傻x 了， 解决了
